### ISSUE TITLE
自动构建部署后少了 images 文件夹和 js 文件夹

### ISSUE THREAD

**Issue by ileadall42** [renzhaosy/hexo-deploy-action#4]
```
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: renzhaosy/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.HEXO_GITHUB_TOKEN }}
        PUBLISH_REPOSITORY: ileadall42/ileadall42.github.io # The repository the action should deploy to.
        BRANCH: master  # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.
```

由于用默认环境变量提示说没有权限，403，所以就自己设定了一个`HEXO_GITHUB_TOKEN`。
**但是自动触发之后，跟正常的文件相差了 2 个文件夹导致没有办法打开：**
正常手动部署如下：
![image](https://user-images.githubusercontent.com/27263086/73602799-4444a280-45b4-11ea-9f5b-9ae6518287ec.png)
使用此 Action 如下：

![image](https://user-images.githubusercontent.com/27263086/73602882-de591a80-45b5-11ea-9807-637a754cff1d.png)
